// Original deterministic procedural sounds. No field recordings or external samples.
// Generated WAV assets are dedicated to CC0-1.0; see public/audio/LICENSE.txt.
import { mkdirSync, writeFileSync } from 'node:fs';
const rate = 22050, tau = Math.PI * 2;
let seed = 721;
const noise = () => { seed = (1664525 * seed + 1013904223) >>> 0; return seed / 2147483648 - 1; };
const wave = (f,t) => Math.sin(tau*f*t);
const env = (t,d) => Math.max(0,Math.min(1,t/.025,(d-t)/.08));
const tone = (t,start,d,f,v=.4) => t>=start && t<start+d ? wave(f,t-start)*env(t-start,d)*v : 0;
mkdirSync('public/audio',{recursive:true});
function save(name,duration,sample) {
 const count=Math.floor(duration*rate), wav=Buffer.alloc(44+count*2);
 wav.write('RIFF');wav.writeUInt32LE(36+count*2,4);wav.write('WAVEfmt ',8);wav.writeUInt32LE(16,16);wav.writeUInt16LE(1,20);wav.writeUInt16LE(1,22);wav.writeUInt32LE(rate,24);wav.writeUInt32LE(rate*2,28);wav.writeUInt16LE(2,32);wav.writeUInt16LE(16,34);wav.write('data',36);wav.writeUInt32LE(count*2,40);
 for(let i=0;i<count;i++) wav.writeInt16LE(Math.round(Math.max(-.95,Math.min(.95,sample(i/rate)))*32767),44+i*2);
 writeFileSync(`public/audio/${name}.wav`,wav);
}
save('door-open',1.5,t=>(noise()*.13+wave(260-t*85,t)*.17)*Math.sin(Math.PI*t/1.5)+tone(t,1.27,.15,110,.2));
save('door-close',1.2,t=>(noise()*.12+wave(150+t*65,t)*.16)*Math.sin(Math.PI*t/1.2)+tone(t,1.05,.12,90,.3));
save('door-warning',2.5,t=>[0,.5,1,1.5,2].reduce((v,start)=>v+tone(t,start,.19,960,.27),0));
save('departure',.8,t=>tone(t,0,.23,660)+tone(t,.26,.38,880));
save('pa-chime',1,t=>tone(t,0,.32,660,.35)+tone(t,.3,.45,880,.3));
save('boarding-tick',.1,t=>tone(t,0,.08,1200,.14));
save('brake',4,t=>(noise()*.22+wave(430,t)*.035)*( .8+.2*wave(1,t)));
save('traction',4,t=>wave(50,t)*.24+wave(100,t)*.11+wave(200,t)*.035+noise()*.025);
// Layered low formant oscillators make an indistinct, speech-like crowd bed.
save('platform',6,t=>{
 let v=0;for(let j=0;j<9;j++) {const pulse=Math.max(0,wave(.5+j/6,t+j*.9));v+=(wave(115+j*21,t)+.3*wave(540+j*55,t))*.025*pulse;}
 return (v+noise()*.018)*(.85+.15*wave(1/6,t));
});
writeFileSync('public/audio/LICENSE.txt','Original procedural audio generated by scripts/generate-audio.mjs for Namma Metro Driver Sim.\nDedicated to the public domain under CC0 1.0 Universal.\nhttps://creativecommons.org/publicdomain/zero/1.0/\nNo third-party samples, recorded voices, or commercial game assets.\n');
console.log('Generated 9 mono PCM WAVs at 22050 Hz.');
