import React, { useCallback, useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import World from './World';
import { routes, duration, motion, type Line } from './routes';
import { audio } from './audio';
import './style.css';
function App(){
 const [line,setLine]=useState<Line>('purple'),[index,setIndex]=useState(0),[elapsed,setElapsed]=useState(0),[traveling,setTraveling]=useState(false),[platform,setPlatform]=useState(false),[paused,setPaused]=useState(false),[locked,setLocked]=useState(false),[muted,setMuted]=useState(false),[started,setStarted]=useState(false),[visited,setVisited]=useState({purple:0,green:0});
 const route=routes[line],last=index===route.stations.length-1,total=duration(route.km[index]??1.2),{progress,speed}=motion(elapsed,total),doors=!traveling;
 const tick=useRef(0);
 useEffect(()=>{if(!traveling||paused)return;tick.current=performance.now();const id=window.setInterval(()=>{const now=performance.now();setElapsed(t=>Math.min(total,t+Math.min((now-tick.current)/1000,.25)));tick.current=now},50);return()=>clearInterval(id)},[traveling,paused,total]);
 useEffect(()=>{if(traveling&&elapsed>=total){setTraveling(false);setElapsed(0);setIndex(i=>i+1);setVisited(v=>({...v,[line]:v[line]+1}));audio.chime(route.stations[index+1]);}},[elapsed,total,traveling,line,index,route]);
 useEffect(()=>{audio.speed(paused?0:speed)},[speed,paused]);
 const toggleMute=useCallback(()=>setMuted(v=>{audio.setMute(!v);return !v}),[]);
 const enterExit=useCallback(()=>{if(!traveling&&started)setPlatform(v=>!v)},[traveling,started]);
 const depart=()=>{if(platform||last)return;audio.chime();setElapsed(0);setTraveling(true);setPaused(false);setStarted(true)};
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.repeat)return;if(e.code==='KeyM')toggleMute();if(e.code==='KeyE')enterExit();if(e.code==='Escape'){setPaused(true);setLocked(false)}};const visibility=()=>{if(document.hidden)setPaused(true)};window.addEventListener('keydown',key);document.addEventListener('visibilitychange',visibility);return()=>{window.removeEventListener('keydown',key);document.removeEventListener('visibilitychange',visibility)}},[toggleMute,enterExit]);
 const switchLine=(next:Line)=>{document.exitPointerLock?.();setLine(next);setIndex(0);setElapsed(0);setTraveling(false);setPlatform(false);setPaused(false);setStarted(true);audio.start()};
 return <main style={{'--line':route.color} as React.CSSProperties}>
  <div className="world"><World state={{line,index,progress,speed:traveling&&!paused?speed:0,traveling,platform,paused,doors}} onLock={()=>{setLocked(true);setPaused(false);setStarted(true);audio.start()}} onUnlock={()=>{setLocked(false);setPaused(true)}}/></div>
  <div className="vignette"/>
  <header><a className="brand" href="./" aria-label="Namma Metro home"><span className="mark">m</span><span>NAMMA METRO<small>ನಮ್ಮ ಮೆಟ್ರೋ</small></span></a><div className="edition">BENGALURU, KA <span>12.97° N / 77.59° E</span></div><button className="sound" onClick={toggleMute} aria-label={muted?'Unmute audio':'Mute audio'}>{muted?'◌':'◖))'} <span>{muted?'SOUND OFF':'SOUND ON'}</span><kbd>M</kbd></button></header>
  <section className="journey"><div className="eyebrow"><span className="live-dot"/> THE EVENING COMMUTE <span className="version">VOL. 01</span></div><h1>A little closer<br/>to <em>home.</em></h1><p>A city in motion. A moment to yourself.</p><div className="line-tabs" role="group" aria-label="Choose metro line"><button className={line==='purple'?'selected':''} onClick={()=>switchLine('purple')}><i className="purple"/>Purple Line</button><button className={line==='green'?'selected':''} onClick={()=>switchLine('green')}><i className="green"/>Green Line</button></div><div className="route-heading"><span>{route.terminals}</span><span>↓</span></div><ol className="stations">{route.stations.map((station,i)=><li key={station} className={`${i===index?'current':''} ${i<index?'done':''}`}><span className="node">{i<index?'✓':''}</span><span>{station}{i===index&&<small>{traveling?'DEPARTED': 'YOU ARE HERE'}{route.underground[i]?' · UNDERGROUND':' · ELEVATED'}</small>}</span>{i===index&&<b>←</b>}</li>)}</ol><div className="trip-meta"><span>{route.stations.length-1} HOPS <b>·</b> {line==='purple'?'ELEVATED → UNDERGROUND':'UNDERGROUND → ELEVATED'}</span><span>~{Math.round(route.km.reduce((a,b)=>a+b,0))} MIN</span></div></section>
  <div className="scene-label"><span className="live-dot"/>{platform?'ON THE PLATFORM':'INSIDE THE COACH'}<span className="scene-detail">{route.underground[index]?'Fluorescent hours':'The golden hour'} / 17:42</span></div>
  <div className="crosshair">+</div>
  {<div className="look-prompt" style={{display:locked?'none':undefined}}><button id="look-button" onClick={()=>{setStarted(true);setPaused(false);audio.start()}}><span>⤢</span> {paused?'Resume & look around':started?'Look around':'Step into the evening'} <span>↗</span></button><p>{paused?'PAUSED · ':''}CLICK TO CAPTURE MOUSE · ESC TO RELEASE</p></div>}
  {locked&&<div className="locked-hint">MOUSE TO LOOK <span>·</span> ESC FOR CONTROLS {doors&&<><span>·</span> E TO {platform?'BOARD':'EXPLORE PLATFORM'}</>}</div>}
  <section className="ride-panel"><div className="status-icon">{traveling?'→':'Ⅱ'}</div><div className="ride-station"><div className="eyebrow">{paused?'JOURNEY PAUSED':traveling?(elapsed<12?'DEPARTING':elapsed>total-12?'ARRIVING':'ON THE MOVE'):last?'HOP SEQUENCE COMPLETE':'DOORS OPEN · MIND THE GAP'}</div><h2>{traveling?route.stations[index+1]:route.stations[index]}</h2><p>{traveling?`From ${route.stations[index]} · ${route.km[index].toFixed(1)} km hop`:last?'Take a breath. Discover the other line.':`Next stop: ${route.stations[index+1]}`}</p></div><div className="ride-right">{traveling?<><strong>{Math.round(speed*(route.km[index]*1000/(total-12))*3.6)}<small> KM/H</small></strong><span>{Math.ceil(total-elapsed)} SEC TO ARRIVAL</span></>:<><button className="depart" onClick={last?()=>switchLine(line==='purple'?'green':'purple'):depart} disabled={platform}>{last?'Discover '+(line==='purple'?'Green':'Purple')+' Line':'Depart for next stop'} <span>→</span></button><button className="platform-button" onClick={()=>{setStarted(true);enterExit();if(!started)setPlatform(true)}}>{platform?'E · Board the coach':'E · Explore platform'}</button></>}</div><div className="progress" style={{width:`${traveling?progress*100:100}%`}}/></section>
  <footer><span><kbd>W</kbd><kbd>A</kbd><kbd>S</kbd><kbd>D</kbd> WALK ON PLATFORM <i/> <kbd>E</kbd> ENTER / EXIT <i/> <kbd>ESC</kbd> PAUSE</span><span className="objective">{visited.purple>0&&visited.green>0?'✓ BOTH LINES DISCOVERED':`DISCOVER BOTH LINES · ${Number(visited.purple>0)+Number(visited.green>0)} / 2`} <b>●</b> A SLOWER WAY THROUGH THE CITY</span></footer>
 </main>
}
createRoot(document.getElementById('root')!).render(<App/>);
